"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$ruby\
$git_branch\
$git_status\
$line_break\
$username\
$hostname\
$character"""

add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bold yellow'

[ruby]
format = '[$version]($style) '
version_format = '${raw}'
style = 'bold underline purple'

[git_branch]
format = '[\[$branch]($style)'
style = 'bold green'

[git_status]
format = '[$stashed( $ahead_behind)\]]($style)'
style = 'bold green'
stashed = ':$count'

[username]
style_user = 'bold blue'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname]($style)'
style = 'bold blue'

[character]
success_symbol = '[\$](bold blue)'
error_symbol = '[\$](bold blue)'
